---
sidebar: sidebar 
permalink: proxmox/proxmox-ontap.html 
keywords: netapp, proxmox, proxmox ve, all-flash, nfs, iscsi, ontap, storage, aff 
summary: 'Fornire storage ONTAP per Proxmox Virtual Environment (VE) utilizzando protocolli NAS (NFS, SMB) e protocolli SAN (FC, iSCSI, NVMe). Selezionare la procedura appropriata specifica del protocollo per configurare l"archiviazione condivisa per il cluster Proxmox VE.' 
---
= Scopri i protocolli di archiviazione per Proxmox VE con NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Fornire storage ONTAP per Proxmox Virtual Environment (VE) utilizzando protocolli NAS (NFS, SMB) e protocolli SAN (FC, iSCSI, NVMe). Selezionare la procedura appropriata specifica del protocollo per configurare l'archiviazione condivisa per il cluster Proxmox VE.

Assicurarsi che gli host Proxmox VE dispongano di FC, Ethernet o altre interfacce supportate cablate agli switch con comunicazione alle interfacce logiche ONTAP . Controllare sempre il https://mysupport.netapp.com/matrix/#welcome["Strumento di matrice di interoperabilità"] per le configurazioni supportate. Gli scenari di esempio vengono creati partendo dal presupposto che su ciascun host Proxmox VE siano disponibili due schede di interfaccia di rete ad alta velocità, collegate tra loro per creare interfacce collegate per la tolleranza agli errori e le prestazioni. Le stesse connessioni uplink vengono utilizzate per tutto il traffico di rete, inclusa la gestione dell'host, il traffico VM/container e l'accesso allo storage. Quando sono disponibili più interfacce di rete, valutare la possibilità di separare il traffico di archiviazione dagli altri tipi di traffico.

Per informazioni sull'architettura di archiviazione ONTAP e sui tipi di archiviazione supportati, vedere link:proxmox-ontap-architecture.html["Scopri di più sull'architettura di archiviazione ONTAP per Proxmox VE"] E link:proxmox-storage-types.html["Scopri i tipi di archiviazione supportati per Proxmox VE"].


NOTE: Quando si utilizza LVM con protocolli SAN (FC, iSCSI, NVMe-oF), il gruppo di volumi può contenere più LUN o namespace NVMe. In tal caso, tutti i LUN o gli spazi dei nomi devono far parte dello stesso gruppo di coerenza per garantire l'integrità dei dati. Non supportiamo gruppi di volumi che si estendono su più ONTAP SVM. Ogni gruppo di volumi deve essere creato da LUN o namespace dello stesso SVM.



== Scegli un protocollo di archiviazione

Seleziona il protocollo più adatto al tuo ambiente e ai tuoi requisiti:

* link:proxmox-ontap-smb.html["Configurare l'archiviazione SMB/CIFS"] - Configurare le condivisioni di file SMB/CIFS per Proxmox VE con supporto multicanale per tolleranza agli errori e prestazioni migliorate su più connessioni di rete.
* link:proxmox-ontap-nfs.html["Configurare l'archiviazione NFS"] - Configurare l'archiviazione NFS per Proxmox VE con nConnect o trunking di sessione per migliorare la tolleranza agli errori e le prestazioni utilizzando più connessioni di rete.
* link:proxmox-ontap-fc.html["Configurare LVM con FC"] - Configurare Logical Volume Manager (LVM) con Fibre Channel per un accesso allo storage a blocchi ad alte prestazioni e bassa latenza su host Proxmox VE.
* link:proxmox-ontap-iscsi.html["Configurare LVM con iSCSI"] - Configurare Logical Volume Manager (LVM) con iSCSI per l'accesso all'archiviazione a blocchi su reti Ethernet standard con supporto multipath.
* link:proxmox-ontap-nvme-fc.html["Configurare LVM con NVMe/FC"] - Configurare Logical Volume Manager (LVM) con NVMe su Fibre Channel per un'archiviazione a blocchi ad alte prestazioni utilizzando il moderno protocollo NVMe.
* link:proxmox-ontap-nvme-tcp.html["Configurare LVM con NVMe/TCP"] - Configurare Logical Volume Manager (LVM) con NVMe su TCP per l'archiviazione a blocchi ad alte prestazioni su reti Ethernet standard utilizzando il moderno protocollo NVMe.

