---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-snapcenter.html 
keywords: netapp, vmware, getting, started 
summary:  
---
= Scopri di più sul backup e il ripristino delle macchine virtuali utilizzando il plug-in SnapCenter per VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Il SnapCenter Plug-in for VMware vSphere consente operazioni di backup e ripristino rapide e coerenti con le VM per VM, datastore e file VMDK.  Questo plug-in VMware si integra con SnapCenter Server per supportare il backup e il ripristino basati sulle applicazioni per i plug-in specifici delle applicazioni SnapCenter .



== Risorse di documentazione

Per informazioni dettagliate, fare riferimento alle seguenti risorse di documentazione.

* link:https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/["Documentazione SnapCenter Plug-in for VMware vSphere"]




== Risorse della soluzione

Fare riferimento alla seguente soluzione di backup 3-2-1 con SnapCenter Plug-in for VMware vSphere e backup e ripristino NetApp per VM.

Rapporto tecnico:link:https://docs.netapp.com/us-en/netapp-solutions-cloud/vmware/vmw-hybrid-321-dp-scv.html["Protezione dei dati 3-2-1 per VMware con plug-in SnapCenter e NetApp Backup and Recovery per VM"^]

Blog Tech ONTAP :link:https://community.netapp.com/t5/Tech-ONTAP-Blogs/3-2-1-Data-Protection-for-VMware-with-SnapCenter-Plug-in-and-BlueXP-backup-and/ba-p/446180["Protezione dei dati 3-2-1 per VMware con plug-in SnapCenter e NetApp Backup and Recovery per VM"]



== Risorse video

.SnapCenter Plug-in for VMware vSphere - Prerequisiti della soluzione
video::38881de9-9ab5-4a8e-a17d-b01200fade6a[panopto]
.SnapCenter Plug-in for VMware vSphere - Distribuzione
video::10cbcf2c-9964-41aa-ad7f-b01200faca01[panopto]
.SnapCenter Plug-in for VMware vSphere - Flusso di lavoro di backup
video::b7272f18-c424-4cc3-bc0d-b01200faaf25[panopto]
.SnapCenter Plug-in for VMware vSphere - Ripristino del flusso di lavoro
video::ed41002e-585c-445d-a60c-b01200fb1188[panopto]
.SnapCenter - Flusso di lavoro di ripristino SQL
video::8df4ad1f-83ad-448b-9405-b01200fb2567[panopto]