---
sidebar: sidebar 
permalink: vmware/vmw-demos-videos.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, BlueXP Copy and Sync, FabricPool, ONTAP 
summary: 'Questa pagina fornisce un"introduzione a video e tutorial.' 
---
= Guarda video e demo sulla virtualizzazione con NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Guarda video e demo che spiegano le caratteristiche importanti delle soluzioni cloud ibride, di virtualizzazione e di container.  Scopri come utilizzare gli strumenti NetApp ONTAP tools for VMware vSphere, il SnapCenter Plug-in for VMware vSphere, la protezione dei dati 3-2-1 e come NetApp interagisce con AWS e Azure.  Ottieni suggerimenti utili per configurare e gestire queste tecnologie.

.Strumenti NetApp ONTAP per VMware vSphere
[%collapsible%open]
====
.Strumenti ONTAP per VMware - Panoramica
video::e8071955-f6f1-45a0-a868-b12a010bba44[panopto]
.Provisioning del datastore iSCSI VMware con ONTAP
video::5c047271-aecc-437c-a444-b01200f9671a[panopto]
.Provisioning del datastore VMware NFS con ONTAP
video::a34bcd1c-3aaa-4917-9a5d-b01200f97f08[panopto]
====
.SnapCenter Plug-in for VMware vSphere
[%collapsible%open]
====
Il software NetApp SnapCenter software è una piattaforma aziendale di facile utilizzo per coordinare e gestire in modo sicuro la protezione dei dati su applicazioni, database e file system.

Il SnapCenter Plug-in for VMware vSphere consente di eseguire operazioni di backup, ripristino e collegamento per le VM, nonché operazioni di backup e montaggio per gli archivi dati registrati con SnapCenter direttamente all'interno di VMware vCenter.

Per ulteriori informazioni sul SnapCenter Plug-in for VMware vSphere-in NetApp SnapCenter per VMware vSphere, vederelink:https://docs.netapp.com/ocsc-42/index.jsp?topic=%2Fcom.netapp.doc.ocsc-con%2FGUID-29BABBA7-B15F-452F-B137-2E5B269084B9.html["SnapCenter Plug-in for VMware vSphere-in NetApp SnapCenter per VMware vSphere"] .

.SnapCenter Plug-in for VMware vSphere - Prerequisiti della soluzione
video::38881de9-9ab5-4a8e-a17d-b01200fade6a[panopto,width=360]
.SnapCenter Plug-in for VMware vSphere - Distribuzione
video::10cbcf2c-9964-41aa-ad7f-b01200faca01[panopto,width=360]
.SnapCenter Plug-in for VMware vSphere - Flusso di lavoro di backup
video::b7272f18-c424-4cc3-bc0d-b01200faaf25[panopto,width=360]
.SnapCenter Plug-in for VMware vSphere - Ripristino del flusso di lavoro
video::ed41002e-585c-445d-a60c-b01200fb1188[panopto,width=360]
.SnapCenter - Flusso di lavoro di ripristino SQL
video::8df4ad1f-83ad-448b-9405-b01200fb2567[panopto,width=360]
====
.Soluzioni di protezione dei dati 3-2-1
[%collapsible%open]
====
Le soluzioni di protezione dei dati 3-2-1 combinano backup primari e secondari in sede, utilizzando la tecnologia SnapMirror , con copie replicate su storage di oggetti tramite BlueXP backup and recovery.

.Protezione dei dati 3-2-1 per datastore VMFS con SnapCenter Plug-in for VMware vSphere e BlueXP Backup e ripristino per macchine virtuali
video::7c21f3fc-4025-4d8f-b54c-b0e001504c76[panopto,width=360]
====
.VMware Cloud su AWS con AWS FSx ONTAP
[%collapsible%open]
====
.Archiviazione connessa guest Windows con FSx ONTAP tramite iSCSI
video::0d03e040-634f-4086-8cb5-b01200fb8515[panopto,width=360]
.Archiviazione connessa guest Linux con FSx ONTAP tramite NFS
video::c3befe1b-4f32-4839-a031-b01200fb6d60[panopto,width=360]
.Risparmio sul TCO di VMware Cloud su AWS con Amazon FSx ONTAP
video::f0fedec5-dc17-47af-8821-b01200f00e08[panopto,width=360]
.Datastore supplementare VMware Cloud su AWS con Amazon FSx ONTAP
video::2065dcc1-f31a-4e71-a7d5-b01200f01171[panopto,width=360]
.Configurazione e distribuzione di VMware HCX per VMC
video::6132c921-a44c-4c81-aab7-b01200fb5d29[panopto,width=360]
.Dimostrazione di migrazione vMotion con VMware HCX per VMC e FSx ONTAP
video::52661f10-3f90-4f3d-865a-b01200f06d31[panopto,width=360]
.Dimostrazione di migrazione a freddo con VMware HCX per VMC e FSx ONTAP
video::685c0dc2-9d8a-42ff-b46d-b01200f056b0[panopto,width=360]
====
.Servizi VMware di Azure su Azure con Azure NetApp Files (ANF)
[%collapsible%open]
====
.Panoramica del datastore supplementare della soluzione Azure VMware con Azure NetApp Files
video::8c5ddb30-6c31-4cde-86e2-b01200effbd6[panopto,width=360]
.Soluzione Azure VMware DR con Cloud Volumes ONTAP, SnapCenter e JetStream
video::5cd19888-8314-4cfc-ba30-b01200efff4f[panopto,width=360]
.Dimostrazione di migrazione a freddo con VMware HCX per AVS e ANF
video::b7ffa5ad-5559-4e56-a166-b01200f025bc[panopto,width=360]
.Dimostrazione vMotion con VMware HCX per AVS e ANF
video::986bb505-6f3d-4a5a-b016-b01200f03f18[panopto,width=360]
.Dimostrazione di migrazione in blocco con VMware HCX per AVS e ANF
video::255640f5-4dff-438c-8d50-b01200f017d1[panopto,width=360]
====
.VMware Cloud Foundation con NetApp ONTAP
[%collapsible%open]
====
.Datastore NFS come storage principale per domini di carichi di lavoro VCF
video::9b66ac8d-d2b1-4ac4-a33c-b16900f67df6[panopto]
.Datastore iSCSI come storage supplementare per domini di gestione VCF
video::1d0e1af1-40ae-483a-be6f-b156015507cc[panopto]
====
.NetApp con VMware Tanzu
[%collapsible%open]
====
VMware Tanzu consente ai clienti di distribuire, amministrare e gestire il proprio ambiente Kubernetes tramite vSphere o VMware Cloud Foundation.  Questo portafoglio di prodotti VMware consente ai clienti di gestire tutti i cluster Kubernetes rilevanti da un unico piano di controllo, scegliendo l'edizione VMware Tanzu più adatta alle proprie esigenze.

Per ulteriori informazioni su VMware Tanzu, vedere https://tanzu.vmware.com/tanzu["Panoramica di VMware Tanzu"^] .  Questa recensione riguarda i casi d'uso, le aggiunte disponibili e altro ancora su VMware Tanzu.

.Come utilizzare vVols con NetApp e VMware Tanzu Basic, parte 1
video::ZtbXeOJKhrc[youtube,width=360]
.Come utilizzare vVols con NetApp e VMware Tanzu Basic, parte 2
video::FVRKjWH7AoE[youtube,width=360]
.Come utilizzare vVols con NetApp e VMware Tanzu Basic, parte 3
video::Y-34SUtTTtU[youtube,width=360]
====
.Cloud Insights NetApp
[%collapsible%open]
====
NetApp Cloud Insights è una piattaforma completa di monitoraggio e analisi progettata per fornire visibilità e controllo sulla tua infrastruttura on-premise e cloud.

.NetApp Cloud Insights - Osservabilità per il data center moderno
video::1e4da521-3104-4d51-8cde-b0e001502d3d[panopto,width=360]
====