---
sidebar: sidebar 
permalink: vmware/vmw-vcf-disaster-recovery.html 
keywords: vmware, vcf, dr, disaster recovery, draas, bluexp 
summary:  
---
= Scopri come proteggere i datastore VMware utilizzando il BlueXP disaster recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Scopri di più sulle soluzioni NetApp per il disaster recovery utilizzando BlueXP disaster recovery per VMware.  Ciò fornisce soluzioni robuste per il disaster recovery mediante replica a livello di blocco da un sito primario a un sito di disaster recovery.

BlueXP DRaaS è un metodo efficace ed economico per proteggere i carichi di lavoro da guasti del sito e problemi di integrità dei dati, compresi gli attacchi ransomware.  Inoltre, NetApp BlueXP DRaaS potenzia questa strategia fornendo una soluzione di disaster recovery gestita e basata sul cloud, che garantisce un ripristino rapido e tempi di inattività minimi durante i disastri.

Per i dettagli tecnici fare riferimento alle seguenti soluzioni.

* link:vmw-disaster-recovery-vmfs.html["DR tramite BlueXP DRaaS per datastore VMFS"]
* link:vmw-disaster-recovery-nfs.html["DR tramite BlueXP DRaaS per datastore NFS"]

