---
sidebar: sidebar 
permalink: vmware/vmw-vcf-viwld-mgmt-supp-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= VMFS su FC come storage supplementare per i Workload e Management Domains VCF utilizzando ONTAP tools for VMware
:allow-uri-read: 




[[vmfs-on-fc-as-supplemental-storage-for-vcf-workload-and-management-domains-using-ontap-tools-for-vmware]]
== VMFS su FC come storage supplementare per i Workload e Management Domains VCF utilizzando ONTAP tools for VMware

[role="lead"]
In questo scenario mostreremo come distribuire un datastore VMFS con backend Fibre Channel (FC) per domini di gestione e carico di lavoro utilizzando strumenti ONTAP .



[[benefits-of-fibre-channel]]
=== Vantaggi del Fibre Channel

*Prestazioni elevate:* FC garantisce velocità di trasferimento dati elevate, rendendolo ideale per applicazioni che richiedono un accesso rapido e affidabile a grandi quantità di dati.

*Bassa latenza:* Latenza molto bassa, fondamentale per le applicazioni che richiedono prestazioni elevate, come database e ambienti virtualizzati.

*Affidabilità:* le reti FC sono note per la loro robustezza e affidabilità, con funzionalità quali ridondanza integrata e correzione degli errori.

*Larghezza di banda dedicata:* FC fornisce larghezza di banda dedicata per il traffico di archiviazione, riducendo il rischio di congestione della rete.

Per ulteriori informazioni sull'utilizzo di Fibre Channel con i sistemi di storage NetApp , fare riferimento a https://docs.netapp.com/us-en/ontap/san-admin/san-provisioning-fc-concept.html["Provisioning SAN con FC"] .



[[scenario-overview]]
=== Panoramica dello scenario

Il datastore supplementare VCF viene predisposto come parte delle operazioni del giorno 2 utilizzando vCenter. Questo scenario comprende i seguenti passaggi di alto livello:

* Distribuzione degli strumenti ONTAP sul dominio di gestione
* Registra i server vCenter di carico di lavoro negli ONTAP tools
* Definisci il backend di archiviazione sul plugin degli strumenti ONTAP per VMware vSphere
* Fornire VMFS sul trasporto FC




[[prerequisites]]
=== Prerequisiti

Questo scenario richiede i seguenti componenti e configurazioni:

* Un sistema di archiviazione ONTAP con porte FC collegate a switch FC.
* SVM creato con FC lifs.
* vSphere con HBA FC collegati agli switch FC.
* Sugli switch FC è configurata la suddivisione in zone con singolo iniziatore-destinazione.
+

NOTE: Utilizzare l'interfaccia logica FC SVM nella configurazione della zona anziché le porte FC fisiche sui sistemi ONTAP .



NetApp consiglia il multipath per le LUN FC.

Per informazioni complete sulla configurazione di Fibre Channel sui sistemi di archiviazione ONTAP , fare riferimento a https://docs.netapp.com/us-en/ontap/san-management/index.html["Gestione dello storage SAN"] nella documentazione ONTAP 9.

Per ulteriori informazioni sull'utilizzo di VMFS con sistemi di archiviazione ONTAP , fare riferimento alink:vmw-vmfs-deploy.html["Guida alla distribuzione per VMFS"] .



[[deployment-steps-for-management-domain]]
=== Fasi di distribuzione per il dominio di gestione

Per distribuire ONTAP Tools e utilizzarlo per creare un datastore VMFS sul dominio di gestione VCF, completare i seguenti passaggi:

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/ontap-tools-deployment.html["Distribuire gli strumenti ONTAP sul dominio di gestione"]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-storage-backend.html["Definisci il backend di archiviazione utilizzando l'interfaccia client vSphere"]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-datastore.html["Provisioning VMFS su FC"]




[[deployment-steps-for-workload-domain]]
=== Passaggi di deployment per il workload domain

Per distribuire ONTAP tools e usarlo per creare un datastore VMFS sul dominio workload VCF, segui questi passaggi:

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-vcenter.html["Registra il carico di lavoro vCenter per abilitare il plugin vCenter"]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-storage-backend.html["Definisci il backend di archiviazione utilizzando l'interfaccia client vSphere"]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-datastore.html["Provisioning VMFS su FC"]




[[additional-information]]
=== Informazioni aggiuntive

Per informazioni sulla configurazione dei sistemi di archiviazione ONTAP fare riferimento alink:https://docs.netapp.com/us-en/ontap["Documentazione ONTAP 9"] centro.

Per informazioni sulla configurazione di VCF fare riferimento alink:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html["Documentazione di VMware Cloud Foundation"] .



[[video-demo-for-this-solution]]
== Demo video per questa soluzione

.Datastore supplementare con FC
video::96311abf-aa45-4ce9-984b-b4b001005bab[panopto,width=360]