---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-principal-nfs.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, nfs 
summary:  
---
= Utilizzare un datastore NFS su ONTAP come storage principale per il dominio di gestione VCF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
In questo caso d'uso, descriviamo la procedura per creare un datastore NFS su ONTAP come storage primario per il dominio di gestione di VMware Cloud Foundation (VCF). Questa procedura riassume i componenti necessari, i passaggi di configurazione e il processo di implementazione.



[[introduction]]
== Introduzione

Ove opportuno, faremo riferimento alla documentazione esterna per i passaggi da eseguire in vCenter e menzioneremo quei passaggi che sono specifici per la parte di configurazione dello storage.

Se devi utilizzare un datastore NFS 4.1 per lo storage primario o se stai convertendo un ambiente vSphere basato su NFS esistente con ONTAP, fai riferimento a link:vmw-vcf-mgmt-nfs.html["Convergi l'ambiente vSphere (datastore NFS) nel dominio di gestione VCF"].


NOTE: La versione 5.2 di VCF ha introdotto la possibilità di convertire un ambiente vSphere 8 esistente in un dominio di gestione VCF o di importarlo come dominio di carico di lavoro VI di VCF. Prima di questa versione, VMware vSAN era l'unica opzione per lo storage primario del dominio di gestione VCF. È meglio distribuire le VM del controller NSX su un datastore VMFS basato su FC oppure usare uno switch di rete doppio per evitare single point of failure. Se queste opzioni non sono disponibili, valuta di usare vSAN per ospitare queste VM.


NOTE: Questa soluzione è applicabile alle piattaforme ONTAP che supportano lo storage NFS, inclusi NetApp AFF, AFX e FAS.



[[prerequisites]]
== Prerequisiti

In questo scenario vengono utilizzati i seguenti componenti e configurazioni:

* Sistema di archiviazione NetApp con una macchina virtuale di archiviazione (SVM) configurata per consentire il traffico NFS.
* È stata creata un'interfaccia logica (LIF) sulla rete IP che deve trasportare il traffico NFS ed è associata all'SVM.
* Un vSphere cluster con almeno 2 x vSphere host.
* Datastore NFS montato su uno degli host vSphere con lo stesso server NFS e percorso di esportazione che verrà utilizzato per il dominio di gestione.



NOTE: Quando distribuisci un dominio VCF, VCF convalida la connettività al server NFS. Questo viene fatto utilizzando l'adattatore di gestione sugli host vSphere prima che venga aggiunto qualsiasi adattatore vmkernel aggiuntivo con l'indirizzo IP NFS. Quindi, è necessario assicurarsi che 1) la rete di gestione sia instradabile verso il server NFS, oppure 2) sia stato aggiunto un LIF per la rete di gestione all'SVM che ospita il volume del datastore NFS, per garantire che la convalida possa procedere.

* Assicurati che lo strumento ONTAP NFS VAAI sia installato su uno degli host vSphere che puoi selezionare come modello per l'immagine del cluster.
* Distribuisci lo strumento VCF Installer.


Per informazioni sulla configurazione dei sistemi di archiviazione ONTAP fare riferimento alink:https://docs.netapp.com/us-en/ontap["Documentazione ONTAP 9"] centro.

Per informazioni sulla configurazione di VCF, fai riferimento a link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["Documentazione di VMware Cloud Foundation"].



[[deployment-steps]]
== Fasi di distribuzione



[[management-domain-default-cluster]]
=== Dominio di gestione - Cluster predefinito

Lo strumento VCF Installer supporta VMFS su FC, datastore NFS v3 e vSAN per il dominio di gestione. I seguenti passaggi descrivono la procedura per distribuire un dominio di gestione con un datastore basato su NFSv3 su ONTAP come storage principale.


NOTE: Convalida o modifica il valore nConnect per il datastore NFS dopo la distribuzione.

Per ulteriori informazioni sull'utilizzo di un ambiente vSphere esistente, consulta link:vmw-vcf-mgmt-nfs.html["Convergi l'ambiente vSphere (datastore NFS) nel dominio di gestione VCF"].



[[management-domain-additional-cluster]]
=== Dominio di gestione - Cluster aggiuntivo

Per espandere il dominio di gestione con un cluster aggiuntivo, fai riferimento a  https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/building-your-private-cloud-infrastructure/working-with-workload-domains/expand-a-workload-domain/add-a-cluster-to-a-workload-domain-using-the-sddc-manager-ui.html["Aggiungi un cluster SDDC a un dominio VCF"].

A livello generale, i passaggi per aggiungere un cluster aggiuntivo al dominio di gestione sono i seguenti: * Assicurati che gli host siano stati commissionati e che i pool di rete siano configurati in vCenter. * Il volume del datastore NFS è stato predisposto sul sistema storage ONTAP ed esportato sugli host nel cluster aggiuntivo. * Crea un nuovo cluster SDDC nel dominio di gestione su vCenter e segui la procedura guidata per aggiungere il cluster aggiuntivo al dominio di gestione.



[[additional-information]]
== Informazioni aggiuntive

Per informazioni sulla configurazione dei sistemi di archiviazione ONTAP fare riferimento alink:https://docs.netapp.com/us-en/ontap["Documentazione ONTAP 9"] centro.

Per informazioni sulla configurazione di VCF, fai riferimento a link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["Documentazione di VMware Cloud Foundation"].
