---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-nfs-requirements.html 
keywords: netapp, vmware, cloud, foundation, vcf, aff, all-flash, nfs, array, ontap tools, otv, sddc, sddc manager, ontap tools, ontap tools 10 
summary: Esaminare i requisiti per la conversione di un cluster vSphere 8 con datastore NFS NetApp ONTAP in un dominio di gestione VMware Cloud Foundation. 
---
= Requisiti di distribuzione per la conversione delle istanze del server vCenter in domini di gestione VCF utilizzando datastore NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esaminare i requisiti per la conversione di un cluster vSphere 8 con datastore NFS NetApp ONTAP in un dominio di gestione VMware Cloud Foundation.

Il processo di conversione richiede un sistema di archiviazione AFF o ASA , SVM e LIF per il traffico FC, zonizzazione NFS sugli switch, un cluster vSphere con host ESXi e vCenter e segmenti di rete dedicati per vMotion.



== Requisiti infrastrutturali

Assicurarsi che i seguenti componenti e configurazioni siano presenti.

* Sistema di archiviazione NetApp AFF con una macchina virtuale di archiviazione (SVM) configurata per consentire il traffico NFS.
* Interfaccia logica (LIF) creata sulla rete IP per trasportare il traffico NFS e associata all'SVM.
* Un cluster vSphere con 4 host ESXi e un'appliance vCenter collocata nel cluster.
* Gruppo di porte distribuito configurato per il traffico di archiviazione vMotion e NFS sulle VLAN o sui segmenti di rete stabiliti a tale scopo.
* Software per la conversione VCF. Per il software richiesto, vai a https://support.broadcom.com/["Portale di supporto Broadcom"] .
* Prerequisiti per gli strumenti ONTAP .
+
Per informazioni complete sui prerequisiti per gli strumenti ONTAP , fare riferimento a https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/prerequisites.html#system-requirements["Prerequisiti per gli ONTAP tools for VMware vSphere"] .

+
Gli ONTAP tools for VMware vSphere possono essere installati in configurazioni HA o non HA.





== Risorse aggiuntive

* Per l'archiviazione supportata e altre considerazioni per la conversione o l'importazione di vSphere in VCF 5.2, fare riferimento a https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2/map-for-administering-vcf-5-2/importing-existing-vsphere-environments-admin/considerations-before-converting-or-importing-existing-vsphere-environments-into-vcf-admin.html["Considerazioni prima di convertire o importare ambienti vSphere esistenti in VMware Cloud Foundation"] .
* Per informazioni sulla configurazione dei sistemi di archiviazione ONTAP , fare riferimento alink:https://docs.netapp.com/us-en/ontap["Documentazione ONTAP 9"] .
* Per informazioni sulla configurazione di VCF, fare riferimento alink:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html["Documentazione di VMware Cloud Foundation 5.2"] .




== Cosa succederà ora?

Dopo aver esaminato i requisiti di distribuzione,link:vmw-vcf-mgmt-nfs-deploy.html["distribuire gli strumenti ONTAP e predisporre il datastore NFS"] .
