---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-principal-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= Utilizzare un datastore VMFS basato su FC su ONTAP come storage principale per il dominio di gestione VCF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
In questo caso d'uso, descriviamo la procedura per creare un datastore VMFS basato su FC su ONTAP come storage primario per il dominio di gestione di VMware Cloud Foundation (VCF). Questa procedura riassume i componenti, le configurazioni e le fasi di implementazione necessari.



[[introduction]]
== Introduzione

Ove opportuno, faremo riferimento alla documentazione esterna per i passaggi da eseguire in vCenter e menzioneremo quei passaggi che sono specifici per la parte di configurazione dello storage.

Per informazioni sulla conversione di un datastore VMFS esistente (inclusi iSCSI e NVMe-oF) in ambiente vSphere con ONTAP, consulta link:vmw-vcf-mgmt-vmfs.html["Convergi l'ambiente vSphere (datastore VMFS) al dominio di gestione VCF"].


NOTE: La versione 5.2 di VCF ha introdotto la possibilità di convertire un ambiente vSphere 8 esistente in un dominio di gestione VCF o di importarlo come dominio di carico di lavoro VI di VCF. Prima di questa versione, VMware vSAN era l'unica opzione per lo storage primario del dominio di gestione VCF. È meglio distribuire le VM del controller NSX su un datastore VMFS basato su FC oppure usare uno switch di rete doppio per evitare single point of failure. Se queste opzioni non sono disponibili, valuta di usare vSAN per ospitare queste VM.


NOTE: Questa soluzione è applicabile alle piattaforme ONTAP che supportano l'archiviazione FC, tra cui NetApp ASA, AFF e FAS.



[[prerequisites]]
== Prerequisiti

In questo scenario vengono utilizzati i seguenti componenti e configurazioni:

* Sistema di storage NetApp con una macchina virtuale di storage (SVM) configurata per consentire il traffico FC.
* Sono state create interfacce logiche (LIF) sulla struttura FC che deve trasportare il traffico FC ed è associata alla SVM.
* La suddivisione in zone è stata configurata per utilizzare la suddivisione in zone con singolo iniziatore-destinazione sugli switch FC per HBA host e destinazioni di archiviazione.


Per informazioni sulla configurazione dei sistemi di archiviazione ONTAP fare riferimento alink:https://docs.netapp.com/us-en/ontap["Documentazione ONTAP 9"] centro.

Per informazioni sulla configurazione di VCF, fai riferimento a link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["Documentazione di VMware Cloud Foundation"].



[[deployment-steps]]
== Fasi di distribuzione



[[management-domain-default-cluster]]
=== Dominio di gestione - Cluster predefinito

Lo strumento VCF Installer supporta VMFS su FC, datastore NFS v3 e vSAN per il dominio di gestione. I seguenti passaggi descrivono la procedura per distribuire un dominio di gestione con un datastore VMFS basato su FC su ONTAP come storage principale.

Per ulteriori informazioni sull'utilizzo di un ambiente vSphere esistente, consulta link:vmw-vcf-mgmt-vmfs.html["Convergi l'ambiente vSphere (datastore VMFS) al dominio di gestione VCF"].



[[management-domain-additional-cluster]]
=== Dominio di gestione - Cluster aggiuntivo

Per espandere il dominio di gestione con un cluster aggiuntivo, fai riferimento a  https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/building-your-private-cloud-infrastructure/working-with-workload-domains/expand-a-workload-domain/add-a-cluster-to-a-workload-domain-using-the-sddc-manager-ui.html["Aggiungi un cluster SDDC a un dominio VCF"].

A livello generale, i passaggi per aggiungere un cluster aggiuntivo al dominio di gestione sono i seguenti: * Assicurati che gli host siano stati commissionati e che i pool di rete siano configurati in vCenter. * Il LUN è stato predisposto sul sistema storage ONTAP e presentato agli host nel cluster aggiuntivo. * Crea un nuovo cluster SDDC nel dominio di gestione su vCenter e segui la procedura guidata per aggiungere il cluster aggiuntivo al dominio di gestione.



[[additional-information]]
== Informazioni aggiuntive

Per informazioni sulla configurazione dei sistemi di archiviazione ONTAP fare riferimento alink:https://docs.netapp.com/us-en/ontap["Documentazione ONTAP 9"] centro.

Per informazioni sulla configurazione di VCF, fai riferimento a link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["Documentazione di VMware Cloud Foundation"].
