---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-nfs-requirements.html 
keywords: netapp, vmware, cloud, foundation, vcf, aff, all-flash, nfs, array, ontap tools, otv, sddc, sddc manager, ontap tools, ontap tools 10 
summary: Esamina i requisiti per la convergenza di un cluster vSphere con datastore NFS NetApp ONTAP a un dominio di gestione VMware Cloud Foundation. 
---
= Requisiti di implementazione per la convergenza dell'istanza server vCenter al dominio di gestione VCF utilizzando i datastore NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esamina i requisiti per la convergenza di un cluster vSphere con datastore NFS NetApp ONTAP a un dominio di gestione VMware Cloud Foundation.

Il processo di convergenza richiede un sistema storage AFF o AFX, SVM e LIF per il traffico NFS, VLAN NFS sugli switch, un vSphere cluster con host vSphere e vCenter, e un segmento di rete dedicato per vMotion.



[[infrastructure-requirements]]
== Requisiti infrastrutturali

Assicurarsi che i seguenti componenti e configurazioni siano presenti.

* NetApp AFF o AFX sistema storage con una macchina virtuale di storage (SVM) configurata per consentire il traffico NFS.
* Interfaccia logica (LIF) creata sulla rete IP per trasportare il traffico NFS e associata all'SVM.
* Un vSphere cluster con almeno 2 x vSphere host e una vCenter appliance collocata nello stesso cluster.
* Gruppo di porte distribuito configurato per il traffico di archiviazione vMotion e NFS sulle VLAN o sui segmenti di rete stabiliti a tale scopo.
* Strumento di installazione VCF per la convergenza del vCenter al dominio di gestione VCF.
* Prerequisiti per gli strumenti ONTAP .
+
Per informazioni complete sui prerequisiti per gli strumenti ONTAP , fare riferimento a https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/prerequisites.html#system-requirements["Prerequisiti per gli ONTAP tools for VMware vSphere"] .

+
Gli ONTAP tools for VMware vSphere possono essere installati in configurazioni HA o non HA.





[[additional-resources]]
== Risorse aggiuntive

* Per informazioni sullo storage supportato e altre considerazioni relative alla convergenza vSphere a VCF, fai riferimento a  https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/deployment/converging-your-existing-vsphere-infrastructure-to-a-vcf-or-vvf-platform-/supported-and-not-supported-configurations.html["Configurazioni supportate e non supportate per la convergenza a VCF"].
* Per informazioni sulla configurazione dei sistemi di archiviazione ONTAP , fare riferimento alink:https://docs.netapp.com/us-en/ontap["Documentazione ONTAP 9"] .
* Per informazioni sulla configurazione di VCF, consulta la link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["Documentazione VMware Cloud Foundation 9.1"].




[[whats-next]]
== Cosa succederà ora?

Dopo aver esaminato i requisiti di distribuzione,link:vmw-vcf-mgmt-nfs-deploy.html["distribuire gli strumenti ONTAP e predisporre il datastore NFS"] .
