---
sidebar: sidebar 
permalink: vmware/vmw-vcf-provision.html 
keywords: vmware, vcf, provision, principal, storage 
summary:  
---
= Fornire un ambiente VCF con ONTAP come soluzione di archiviazione principale
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp ONTAP storage è la soluzione di storage primario ideale per i domini di gestione e workload di VMware Cloud Foundation (VCF). ONTAP offre prestazioni elevate, scalabilità, gestione avanzata dei dati e integrazione perfetta per migliorare l'efficienza operativa e la protezione dei dati.

Per i dettagli tecnici sul provisioning di un ambiente VCF nel dominio appropriato e con il protocollo appropriato, fare riferimento alle seguenti soluzioni.

* link:vmw-vcf-mgmt-principal-fc.html["Dominio di gestione con FC"]
* link:vmw-vcf-mgmt-principal-nfs.html["Dominio di gestione con NFS"]
* link:vmw-vcf-viwld-principal-fc.html["Workload Domain con FC"]
* link:vmw-vcf-viwld-principal-nfs.html["Workload Domain con NFS"]

