---
sidebar: sidebar 
permalink: vmware/vmw-vcf-viwld-principal-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= Usa un datastore VMFS basato su FC su ONTAP come storage primario per un workload domain VCF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
In questo caso d'uso, descriviamo la procedura per configurare un datastore VMFS Fibre Channel (FC) su ONTAP come soluzione di storage primario per un workload domain VMware Cloud Foundation (VCF). Questa procedura riassume i componenti necessari, i passaggi di configurazione e il processo di implementazione.



[[benefits-of-fibre-channel]]
== Vantaggi del Fibre Channel

*Prestazioni elevate:* FC garantisce velocità di trasferimento dati elevate, rendendolo ideale per applicazioni che richiedono un accesso rapido e affidabile a grandi quantità di dati.

*Bassa latenza:* Latenza molto bassa, fondamentale per le applicazioni che richiedono prestazioni elevate, come database e ambienti virtualizzati.

*Affidabilità:* le reti FC sono note per la loro robustezza e affidabilità, con funzionalità quali ridondanza integrata e correzione degli errori.

*Larghezza di banda dedicata:* FC fornisce larghezza di banda dedicata per il traffico di archiviazione, riducendo il rischio di congestione della rete.

Per ulteriori informazioni sull'utilizzo di Fibre Channel con i sistemi di storage NetApp , fare riferimento a https://docs.netapp.com/us-en/ontap/san-admin/san-provisioning-fc-concept.html["Provisioning SAN con FC"] .



[[scenario-overview]]
== Panoramica dello scenario

Questo scenario comprende i seguenti passaggi di alto livello:

* Creare una macchina virtuale di archiviazione (SVM) con interfacce logiche (LIF) per il traffico FC.
* Raccogliere le informazioni WWPN degli host da distribuire e creare i gruppi di iniziatori corrispondenti sul sistema di archiviazione ONTAP .
* Creare un volume FC sul sistema di archiviazione ONTAP .
* Mappa i gruppi initiator al volume FC creato.
* Utilizzare la suddivisione in zone con singolo iniziatore-target sugli switch FC.  Creare una zona per ogni iniziatore (zona iniziatore singolo).
+
** Per ogni zona, includere un target che sia l'interfaccia logica ONTAP FC (WWPN) per gli SVM.  Dovrebbero esserci almeno due interfacce logiche per nodo per SVM.  Non utilizzare il WWPN delle porte fisiche.


* Crea un pool di rete per il traffico vMotion in vCenter.
* Commissiona gli host in vCenter per l'utilizzo in un Workload Domain.
* Distribuisci un dominio di carico di lavoro in VCF Ops utilizzando un datastore VMFS su FC come storage primario.



NOTE: Questa soluzione è applicabile alle piattaforme ONTAP che supportano lo storage FC, tra cui NetApp ASAr2, AFF e FAS.



[[prerequisites]]
== Prerequisiti

In questo scenario vengono utilizzati i seguenti componenti e configurazioni:

* Un sistema storage ONTAP AFF, ASA o FAS con porte FC collegate a switch FC.
* SVM creato con FC lifs.
* vSphere con HBA FC collegati agli switch FC.
* Sugli switch FC è configurata la suddivisione in zone con singolo iniziatore-destinazione.
* Assicurati che la policy di multipathing SVM sia impostata su attivo-attivo.



NOTE: NetApp consiglia il multipath per le LUN FC.



[[deployment-steps]]
== Fasi di distribuzione



[[vcf-workload-domain-default-cluster]]
=== VCF Workload Domain - Cluster predefinito

Dopo che il dominio di gestione è attivo e funzionante, puoi creare il dominio di carico di lavoro VCF:

* Utilizzando l'interfaccia utente VCF Ops. Gli host vSphere vengono commissionati in vCenter e il pool di rete viene configurato. Usa System Manager o l'API ONTAP per distribuire una LUN agli host vSphere.
* Importa un ambiente vSphere esistente come nuovo dominio di workload. Puoi utilizzare ONTAP tools for VMware vSphere, System Manager o l'API ONTAP per distribuire il datastore VMFS nel cluster vSphere.




[[vcf-workload-domain-additional-cluster]]
=== VCF Workload Domain - Cluster aggiuntivo

Per espandere il dominio del carico di lavoro con un cluster aggiuntivo, fai riferimento a  https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/building-your-private-cloud-infrastructure/working-with-workload-domains/expand-a-workload-domain/add-a-cluster-to-a-workload-domain-using-the-sddc-manager-ui.html["Aggiungi un cluster SDDC a un dominio VCF"].

A livello generale, i passaggi per aggiungere un cluster aggiuntivo al workload domain sono i seguenti: * Assicurati che gli host siano stati commissionati e che i pool di rete siano configurati in vCenter. * Il LUN è stato predisposto sul sistema storage ONTAP e presentato agli host nel cluster aggiuntivo. * Crea un nuovo cluster SDDC sul workload domain su vCenter e segui la procedura guidata per aggiungere il cluster aggiuntivo al workload domain.



[[additional-information]]
== Informazioni aggiuntive

Per informazioni sulla configurazione dei sistemi di archiviazione ONTAP fare riferimento alink:https://docs.netapp.com/us-en/ontap["Documentazione ONTAP 9"] centro.

Per informazioni sulla configurazione di VCF, fai riferimento a link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["Documentazione di VMware Cloud Foundation"].
