---
sidebar: sidebar 
permalink: videos/hybrid-cloud-videos.html 
summary: Video e demo che mostrano le soluzioni di virtualizzazione cloud ibrida con NetApp 
keywords: hybrid cloud, rosa, fsx ontap, azure vmware, netapp hci, videos, demos 
---
= Guarda i video sulla virtualizzazione ibrida multiCloud con NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Scopri come NetApp consente la virtualizzazione del cloud ibrido sulle principali piattaforme multicloud ibride.  Guarda i video che illustrano Red Hat OpenShift Service on AWS (ROSA) con le soluzioni FSx ONTAP e NetApp HCI per carichi di lavoro virtualizzati.



== Red Hat OpenShift Service su AWS (ROSA) con FSx ONTAP

.Amazon FSx for NetApp ONTAP con Red Hat OpenShift Service su AWS utilizzando Hosted Control Plane
video::213061d2-53e6-4762-a68f-b21401519023[panopto,width=360]
.Integrazione di FSx ONTAP con Trident
video::621ae20d-7567-4bbf-809d-b01200fa7a68[panopto,width=360]
.Snapshot/ripristino per applicazioni su cluster Red Hat OpenShift Service on AWS (ROSA) con storage Amazon FSx ONTAP
video::36ecf505-5d1d-4e99-a6f8-b11c00341793[panopto,width=360]
.Failover e fail-back delle app su ROSA con FSx ONTAP
video::e9a07d79-42a1-4480-86be-b01200fa62f5[panopto,width=360]


== Soluzioni NetApp HCI

.NetApp HCI per Red Hat OpenShift su Red Hat Virtualization
video::13b32159-9ea3-4056-b285-b01200f0873a[panopto,width=360]