---
sidebar: sidebar 
permalink: opennebula/opennebula-ontap-fc.html 
keywords: netapp, opennebula, lvm thin, fc, fibre channel, lvm, ontap, storage 
summary: 'Configura il datastore Logical Volume Manager (LVM) con Fibre Channel per OpenNebula utilizzando ONTAP. Questa procedura include la configurazione multipath, il provisioning delle LUN, la configurazione degli igroup e la creazione del volume group per il datastore condiviso.' 
---
= Configurare LVM Thin con ONTAP FC per OpenNebula
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Configura il datastore Logical Volume Manager (LVM) per lo storage condiviso tra host OpenNebula utilizzando il protocollo Fibre Channel con NetApp ONTAP. Questa configurazione consente l'accesso allo storage a livello di blocco dalle performance elevate e a bassa latenza.



== Attività iniziali dell'amministratore della virtualizzazione

Completare queste attività iniziali per preparare gli host OpenNebula alla connettività FC e raccogliere le informazioni necessarie per l'amministratore dello storage.

. Verificare che siano disponibili due interfacce HBA.
. Assicurarsi che multipath-tools sia installato su tutti gli host OpenNebula e venga avviato all'avvio.
+
[role="tabbed-block"]
====
.Debian/Ubuntu
--
[source, shell]
----
apt list | grep multipath-tools
# If need to install, execute the following line.
apt-get install multipath-tools
# If /etc/multipath.conf is not present, first make sure the multipathd service is started.
systemctl enable --now multipathd
----
--
.RHEL/AlmaLinux
--
[source, shell]
----
dnf list installed | grep device-mapper-multipath
# If need to install, execute the following line.
dnf install device-mapper-multipath
# If /etc/multipath.conf is not present, first make sure the multipathd service is started.
systemctl enable --now multipathd
----
--
====
. Raccogli il WWPN per tutti gli host OpenNebula e fornisci queste informazioni all'amministratore dello storage e all'amministratore che si occupa della suddivisione in zone del fabric.
+
[source, shell]
----
cat /sys/class/fc_host/host*/port_name
----




== Attività dell'amministratore dell'archiviazione

Se non hai familiarità con ONTAP, utilizza System Manager per un'esperienza migliore.

. Assicurarsi che l'SVM sia disponibile con il protocollo FC abilitato. Seguire link:https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["Documentazione ONTAP 9"].
. Creare due LIF per controller dedicati a FC. Raccogliere gli indirizzi WWPN per i LIF FC creati e fornirli all'amministratore che si occupa della zonizzazione del fabric.
. Crea un igroup e popola gli initiator FC dell'host. Tipicamente viene creato un igroup per un OpenNebula cluster. Includi i server frontend e gli host hypervisor nello stesso igroup per supportare sia i datastore Image che System.
. Creare la LUN con la dimensione desiderata sulla SVM e presentarla all'igroup creato nel passaggio precedente. Assicurarsi che la protezione anti-ransomware sia abilitata nella scheda sicurezza per i sistemi ASA e nella scheda sicurezza del volume per i sistemi AFF/ FAS .
. Notificare all'amministratore della virtualizzazione che la LUN è stata creata.




== Attività finali dell'amministratore della virtualizzazione

Completa queste attività per configurare la LUN FC come datastore LVM condiviso in OpenNebula.

. Accedi tramite SSH a tutti i server OpenNebula e completa i seguenti passaggi su ciascun host.
. Eseguire  `rescan-scsi-bus.sh` o  `echo "- - -" > /sys/class/scsi_host/host*/scan` per ripetere la scansione del bus SCSI e rilevare nuovi LUN.
. Verificare che la LUN sia visibile su tutti gli host OpenNebula utilizzando  `lsblk -S` o il comando fdisk -l. Annotare il nome del dispositivo (ad esempio, sde, sdf) per la LUN creata.
. Aggiungi il dispositivo alla configurazione multipath eseguendo  `multipath -a /dev/<device_name>`. Quindi, esegui  `multipath -r` per ricaricare la configurazione multipath. Verifica la configurazione multipath eseguendo il comando  `multipath -ll`.
. Accedere tramite SSH a uno dei server frontend e creare un file di configurazione in base al tipo di Datastore desiderato. Per un elenco completo degli attributi, fare riferimento a  https://docs.opennebula.io/7.0/product/cluster_configuration/san_storage/lvm_drivers/["OpenNebula LVM documentazione"]. Di seguito sono riportati file di esempio:
+
[role="tabbed-block"]
====
.Backup
--
.. Per Restic,


[listing]
----
$cat fc-restic.conf
NAME = "Backup-Restic-FC"
TYPE = "BACKUP_DS"

DS_MAD = "restic"
TM_MAD = "-"

RESTIC_PASSWORD = "<restic_password>"
RESTIC_SFTP_SERVER = "<backup server>"
----
.. Per Rsync,


[listing]
----
$cat fc-rsync.conf
NAME = "Backup-Rsync-FC"
TYPE = "BACKUP_DS"

DS_MAD = "rsync"
TM_MAD = "-"

RSYNC_USER = "<rsync_user>"
RSYNC_HOST = "<backup server>"
----
--
.File
[source, shell]
----
$cat fc-kernel.conf
NAME = "File-Kernel-FC"
TYPE = "FILE_DS"
DS_MAD = "fs"
TM_MAD = "local"
SAFE_DIRS = "/var/tmp/files"
----
.Immagine
[source, shell]
----
$cat fc-image.conf
NAME = "Image-FC01"
TYPE = "IMAGE_DS"
DS_MAD = "fs"
TM_MAD = "fs_lvm_ssh"
DISK_TYPE = "block"
LVM_THIN_ENABLE = "yes"
----
.Sistema
[source, shell]
----
$cat fc-system.conf
NAME = "System-FC02"
TYPE = "SYSTEM_DS"
TM_MAD = "fs_lvm_ssh"
DISK_TYPE = "block"
BRIDGE_LIST = "<space-separated list of OpenNebula hosts>" # If LUN not presented to frontend hosts
LVM_THIN_ENABLE = "yes"
----
====
. Esegui `onedatastore create <configuration file>`. Nota l'ID del datastore restituito dopo la creazione.
+
[]
====
onedatastore create fc-system.conf ID: 107

====
. Creare un gruppo di volumi sulla LUN FC utilizzando  `vgcreate <vg_name> <multipath_device>` comando. Per i datastore di immagini, il nome del gruppo di volumi può essere qualsiasi nome desiderato. Per i datastore di sistema, il nome del gruppo di volumi deve essere nel formato  `vg-one-<datastore id>`. Questo è necessario per OpenNebula identificare il gruppo di volumi corretto per i datastore di sistema. Procedere con i passaggi seguenti se si sta creando un datastore di backup/file/immagine. Per i datastore di sistema, fermarsi qui.
. Crea un pool thin di volumi logici utilizzando il comando  `lvcreate -l 100%FREE -n <logical volume name> <volume group name>`. Per i System datastore, OpenNebula crea automaticamente il thin pool LVM quando necessario.
. Creare un file system sul volume logico utilizzando il comando  `mkfs.ext4 /dev/<volume group>/<logical volume>`. I datastore di sistema non richiedono la creazione di un file system.
. Aggiornare /etc/fstab o la configurazione di automount per montare il datastore con le opzioni di montaggio desiderate. Si presume che la posizione predefinita del datastore sia /var/lib/one/datastores. Può essere convalidato con `onedatastore show <datastore_id>`. In caso contrario, controllare il parametro DATASTORE_LOCATION in /etc/one/oned.conf. Assicurarsi che la cartella <datastore_id> esista nella posizione dei datastores. Di seguito sono riportate voci di esempio:
+
[role="tabbed-block"]
====
.Utilizzo di /etc/fstab
--
[source, shell]
----
/dev/<vg name>/<logical volume> /var/lib/one/datastores/<datastore_id> ext4 _netdev,noauto,x-systemd.automount,nofail 0 2
----
--
.Utilizzo di automount
--
[source, shell]
----
/var/lib/one/datastores/<datastore_id> -fstype=ext4,_netdev,noauto,x-systemd.automount,nofail,rw :/dev/<vg name>/<logical volume>
----
--
====
. Montare il datastore utilizzando  `mount -a` o  `systemctl reload autofs` comando.
. Verificare che il datastore sia montato con il comando mount e verificare la capacità del datastore con il comando  `onedatastore show <datastore_id>`.
. Assicurarsi che l'utente e il gruppo oneadmin siano proprietari della cartella del datastore. Regolare le autorizzazioni utilizzando il comando  `chown -R oneadmin:oneadmin /var/lib/one/datastores/<datastore_id>`.

